### PR TITLE
Update travis to build on 8

### PR DESCRIPTION
**Pull request by gergelyke**
Adds support for LTS Node.js

### CODE REVIEW

**Comment by gergelyke** [comment]
@NatalieWolfe @lykkin can you take a look please? Node.js 8 became LTS, and as we already made the switch we don't have VM metrics.

**Comment by lykkin** [comment]
@gergelyke Hey thanks for the contribution!  This should definitely be tested against node v8, good catch!

**Comment by gergelyke** [comment]
thanks @lykkin ! can you also create a release out of it, so the binaries gets published too for Node.js 8?

**Comment by gergelyke** [comment]
or do they get published once landed in master?

**Comment by gergelyke** [comment]
it seems like the tests are a bit flaky, and now it failed on master - can you rerun it please? :)

**Comment by lykkin** [comment]
@gergelyke Compiled binaries are pushed up on tags, though the binaries aren't currently pulled down by the install script.  We want to ensure that the pre-built binary code doesn't break things before turning it on for everyone.

If you would like to try out the pre-built binary download you can remove the `--no-download` flag from [this line](https://github.com/newrelic/node-native-metrics/blob/master/package.json#L16) in a branch and install from that.

I'll look into releasing this in the near future so we get some binaries up for node 8.

Thanks again for the pr!

**Pull request merged**
