### PR TITLE
Upgrade `nan` and `segfault-handler`

### PR DESCRIPTION
**Pull request by abetomo**
I upgraded because the build fails in Node.js12.

### CODE REVIEW

**Comment by jbecwar** [comment]
I'm also experiencing the failing to build in node 12. Can we get this merged?

**Comment by abetomo** [comment]
Could you review it?

**Comment by maxgalbu** [comment]
Heeeeey

**Comment by michaelgoin** [comment]
@abetomo Thank you for the PR. We will aim to be more responsive, next time.

We are taking care of this as a part of our official Node 12 support effort and will be including a slightly newer version of one of the libraries. As such, we won't be landing this PR but we do appreciate you taking the time to put this together.

Thank you,

Michael

**Pull request closed without merging**
