### PR TITLE
Adds code of conduct

### PR DESCRIPTION
**Pull request by michaelgoin**
* Added code of conduct file.

Closes: https://github.com/newrelic/node-native-metrics/issues/82

### CODE REVIEW

**Comment by michaelgoin** [comment]
@michaelgoin I'm curious why this was closed and not merged?

**Comment by michaelgoin** [comment]
@carlonewrelic i'm curious why this was closed and not merged?

**Comment by carlonewrelic** [comment]
> @carlonewrelic i'm curious why this was closed and not merged?

Wrong button :)

**Comment by michaelgoin** [comment]
i figured but maybe it was that bad... haha 🤷

**Pull request merged**
