### PR TITLE
Mod: download to allow http and https hosts (fixes #51 pending merge with master)

### PR DESCRIPTION
**Pull request by guilhermehn**

### CODE REVIEW

**Comment by NatalieWolfe** [comment]
Thank you for picking this up! I'll make sure this gets released soon.

**Comment by amalheiros** [comment]
+1 awaiting this release too!

**Comment by amalheiros** [comment]
> Thank you for picking this up! I'll make sure this gets released soon.

+1 awaiting this release too!

**Comment by NatalieWolfe** [comment]
Release PR is up now (#59). Note that you will need `newrelic` version 5.2.0 or greater to get this change since it is on v4 of this module.

**Pull request merged**
