### PR TITLE
Supresses warnings during installation on alpine

### PR DESCRIPTION
**Pull request by eyedean**
## Proposed Release Notes
* Supressing warnings during installation on alpine docker image

## Links
See https://github.com/nodejs/nan/issues/807 for the `nan` issue, and https://github.com/newrelic/node-native-metrics/issues/62#issuecomment-680319480 for detailed conversation.

## Details
Inspired by https://github.com/DataDog/dd-trace-js/pull/943/files

### CODE REVIEW

**Comment by eyedean** [comment]
I have a Mac machine and I tried testing building and testing it on Linux docker containers, but I wasn't very successful.  On alpine, it was failing at: 
```
> segfault-handler@1.3.0 install /root/node-native-metrics/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory '/root/node-native-metrics/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
../src/segfault-handler.cpp:23:10: fatal error: execinfo.h: No such file or directory
   23 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [segfault-handler.target.mk:115: Release/obj.target/segfault-handler/src/segfault-handler.o] Error 1
make: Leaving directory '/root/node-native-metrics/node_modules/segfault-handler/build'
``` 

on slim (and `node:14` default container),  it was failing on tests as in:
```

 FAIL  tests/unit/gc-metrics.tap.js
Cannot find module '/root/n/node-native-metrics/build/Release/_newrelic_native_metrics-5_3_0-native_metrics-83-linux-x64.node' Require stack: - /root/n/node-native-metrics/lib/pre-build.js - /root/n/node-native-metrics/index.js - /root/n/node-native-metrics/tests/unit/gc-metrics.tap.js

  test: GC Metrics
  stack: >
    Error:
        Object.load (lib/pre-build.js:91:10)
        Object.<anonymous> (index.js:6:24)
        Object.Module._compile (node_modules/source-map-support/source-map-support.js:547:25)
  code: MODULE_NOT_FOUND
  requireStack:
    - /root/n/node-native-metrics/lib/pre-build.js
    - /root/n/node-native-metrics/index.js
    - /root/n/node-native-metrics/tests/unit/gc-metrics.tap.js
  tapCaught: testFunctionThrow

 FAIL  tests/unit/gc-metrics.tap.js 1 failed of 1 171.585ms
Cannot find module '/root/n/node-native-metrics/build/Release/_newrelic_native_metrics-5_3_0-native_metrics-83-linux-x64.node' Require stack: - /root/n/node-native-metrics/lib/pre-build.js - /root/n/node-native-metrics/index.js - /root/n/node-native-metrics/tests/unit/gc-metrics.tap.js

 PASS  tests/unit/licenses.tap.js 2 OK 28.035ms
 FAIL  tests/unit/loop-metrics.tap.js
Cannot find module '/root/n/node-native-metrics/build/Release/_newrelic_native_metrics-5_3_0-native_metrics-83-linux-x64.node' Require stack: - /root/n/node-native-metrics/lib/pre-build.js - /root/n/node-native-metrics/index.js - /root/n/node-native-metrics/tests/unit/loop-metrics.tap.js

  test: Loop Metrics
  stack: >
    Error:
        Object.load (lib/pre-build.js:91:10)
        Object.<anonymous> (index.js:6:24)
        Object.Module._compile (node_modules/source-map-support/source-map-support.js:547:25)
  code: MODULE_NOT_FOUND
  requireStack:
    - /root/n/node-native-metrics/lib/pre-build.js
    - /root/n/node-native-metrics/index.js
    - /root/n/node-native-metrics/tests/unit/loop-metrics.tap.js
  tapCaught: testFunctionThrow
```

I hope someone can verify that it's not causing any harm on linux machines and works flawlessly. :)

**Comment by eyedean** [comment]
CLA is signed.

**Comment by astormnewrelic** [comment]
Thanks for putting this PR together @eyedean -- adding `-Wno-cast-function-type` to surpress build warnings makes sense. Our CI is passing and I ran some test on my mac as well as some tests in linux containers and everything appears to be running smoothly (or as smoothly as things were prior to this change w/r/t to Alpine) 

While this doesn't add full "drop in" alpine support it does move us incrementally forward so we're going to approve and merge.  The rest of this message is some diagnosing of the errors you saw in case it helps future folks.  

```
make: Entering directory '/root/node-native-metrics/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
../src/segfault-handler.cpp:23:10: fatal error: execinfo.h: No such file or directory
   23 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
```

This looks like our `devDependency` on the [`segfault-handler`](https://www.npmjs.com/package/segfault-handler) project won't build. This project wants to use the `execinfo` library.  I'm guessing there's not a [`musl`](https://alpinelinux.org/posts/Alpine-Linux-has-switched-to-musl-libc.html) equivalent for this, so the compile fails. This problem was not introduced by your change.  

---

```
 FAIL  tests/unit/gc-metrics.tap.js 1 failed of 1 171.585ms
Cannot find module '/root/n/node-native-metrics/build/Release/_newrelic_native_metrics-5_3_0-native_metrics-83-linux-x64.node' Require stack: - /root/n/node-native-metrics/lib/pre-build.js - /root/n/node-native-metrics/index.js - /root/n/node-native-metrics/tests/unit/gc-metrics.tap.js
```

The error's basically saying that it can't find the built native metrics module, so it can't run the tests (`_newrelic_native_metrics-5_3_0-native_metrics-83-linux-x64.node`).

I've seen this before when I failed to run `npm install/npm build` before running my tests.  

I've also seen it when I've run those commands on my mac but then tried to run things inside a linux docker container. (i.e. a module built for the mac, but not for linux)

**Comment by astormnewrelic** [comment]
OK -- this is promising, with this branch, I could do the following

```
$ docker run -v `pwd`:/project -it node:14.8.0-alpine3.12 sh

# apk update
# apk add python2 g++ make
# apk add libexecinfo libexecinfo-dev	# needed for `segfault-handler`

# cd /project
# rm -rf node_modules build
# npm install 					# will see warnings related to install of segfault-handler, 
			  				# but still compiles
			  			  
# npm run build
```

and the native metrics module build correctly.  The key was `libexecinfo libexecinfo-dev`, which appears to give Alpine the  `execinfo.h` header it needs.  I [found that information here](https://github.com/ddopson/node-segfault-handler/pull/67).

It sounds like `segfault-handler` could use the same/similar warning suppression as the ones in this PR.

**Pull request merged**
