### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by 0x7f**
Fixed one compiler error and two minor compiler warnings.

With this patch, I get nodejs GC and Eventloop stats from Windows machines 👍

### CODE REVIEW

**Comment by NatalieWolfe** [comment]
Thanks for the contribution! This looks good to me.

**Comment by 0x7f** [comment]
Thanks for the quick merge. Can you tell already when you will release the next version containing this patch?

**Comment by NatalieWolfe** [comment]
Can't guarantee it, but very likely early this week. I don't think there is anything holding it back.

**Comment by NatalieWolfe** [comment]
@0x7f We've released 2.1.1 with this fix. Our tests show it installs on Windows now, let me know if it works for you too!

**Pull request merged**
